default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46539_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46539_test
  checkout_timeout: 5.0  # コネクションが使用中の場合、解放を待つ最大時間（秒）
  pool: 5               # 同時に持てるコネクション数の上限（通常はデフォルトでOKだが念のため確認）

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
